In [3]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
import sys
_here = Path.cwd().resolve()
_root = next(p for p in [_here, *_here.parents] if (p / "src").is_dir())
sys.path.insert(0, str(_root / "src"))

import pandas as pd
from regression_modelling.data_wrangling.transit.build import build_all_transit
from regression_modelling.constants import FEATURE_SOURCES
from regression_modelling.data_wrangling import sources, features
from regression_modelling.bias_testing.data import build_protected_table
from crime_blockgroup_mapping.config import INTERIM_DIR
from crime_blockgroup_mapping.constants import UCR_YEAR

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
# Rebuilding transit files
build_all_transit(refresh=True)   # rebuilds data/interim/sources/transit.parquet from the new zips

transit: facility 'convenience' unavailable (Forbidden); H1/H3 skipped for it
transit: facility 'liquor' unavailable (Forbidden); H1/H3 skipped for it
transit: facility 'atm' unavailable (Forbidden); H1/H3 skipped for it
transit[chicago]: reading 1 feed(s)
  mdb-389-20260917.zip: date=20260528 stops=10827 overnight=7586
transit[chicago]: 10827 stops -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/transit/stops/chicago.parquet
Chicago state block groups loaded: 9,896
Chicago city boundary loaded: 1 row(s)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Block groups within city: 2,164 / 9,896
transit[chicago]: stops matched to a within-city BG: 9,971 / 10,827
transit[chicago]: BG table (2164, 12) (2009 BGs with >=1 stop)
transit[houston]: reading 1 feed(s)
  mdb-2060-20260917.zip: date=20260608 stops=8797 overnight=5958
transit[houston]: 8797 stops -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/transit/stops/houston.parquet
Houston state block groups loaded: 18,626
Houston city boundary loaded: 1 row(s)
Block groups within city: 1,629 / 18,626

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

transit[houston]: stops matched to a within-city BG: 7,853 / 8,797
transit[houston]: BG table (1629, 12) (1279 BGs with >=1 stop)
transit[atlanta]: reading 1 feed(s)
  mdb-368-20260917.zip: date=20260420 stops=6924 overnight=6371
transit[atlanta]: 6924 stops -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/transit/stops/atlanta.parquet
Atlanta state block groups loaded: 7,441
Atlanta city boundary loaded: 1 row(s)
Block groups within city: 426 / 7,441
transit[atlanta]: stops matched to a within-city BG: 2,504 / 6,924

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

transit[atlanta]: BG table (426, 12) (358 BGs with >=1 stop)
transit[san_francisco]: reading 2 feed(s)
  mdb-2886-202511251947.zip: date=20250901 stops=3214 overnight=1861
  mdb-53-20260917.zip: date=20260112 stops=50 overnight=50
  deduped 52 shared cross-operator station(s)
transit[san_francisco]: 3212 stops -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/transit/stops/san_francisco.parquet
San Francisco state block groups loaded: 25,586
San Francisco city boundary loaded: 1 row(s)
Block groups within city: 679 / 25,586
transit[san_francisco]: stops matched to a within-city BG: 3,155 / 3,212
transit[san_francisco]: BG table (679, 12) (620 BGs with >=1 stop)
transit[pittsburgh]: reading 1 feed(s)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

  mdb-409-20260917.zip: date=20260223 stops=6418 overnight=3258
transit[pittsburgh]: 6418 stops -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/transit/stops/pittsburgh.parquet
Pittsburgh state block groups loaded: 10,172
Pittsburgh city boundary loaded: 1 row(s)
Block groups within city: 317 / 10,172
transit[pittsburgh]: stops matched to a within-city BG: 2,676 / 6,418
transit[pittsburgh]: BG table (317, 12) (299 BGs with >=1 stop)
transit[jacksonville]: reading 1 feed(s)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

  tld-764-20260917.zip: date=20230704 stops=2390 overnight=886
transit[jacksonville]: 2390 stops -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/transit/stops/jacksonville.parquet
Jacksonville state block groups loaded: 13,350
Jacksonville city boundary loaded: 1 row(s)
Block groups within city: 550 / 13,350
transit[jacksonville]: stops matched to a within-city BG: 2,291 / 2,390
transit[jacksonville]: BG table (550, 12) (386 BGs with >=1 stop)
transit[kansas_city]: reading 1 feed(s)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

  mdb-187-20260917.zip: date=20260406 stops=2283 overnight=396
transit[kansas_city]: 2283 stops -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/transit/stops/kansas_city.parquet
Kansas City state block groups loaded: 5,031
Kansas City city boundary loaded: 1 row(s)
Block groups within city: 473 / 5,031
transit[kansas_city]: stops matched to a within-city BG: 1,903 / 2,283
transit[kansas_city]: BG table (473, 12) (321 BGs with >=1 stop)
transit[sacramento]: reading 1 feed(s)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

  mdb-2137-20260917.zip: date=20250404 stops=2821 overnight=86
transit[sacramento]: 2821 stops -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/transit/stops/sacramento.parquet
Sacramento state block groups loaded: 25,586
Sacramento city boundary loaded: 1 row(s)
Block groups within city: 366 / 25,586
transit[sacramento]: stops matched to a within-city BG: 1,502 / 2,821
transit[sacramento]: BG table (366, 12) (303 BGs with >=1 stop)
transit[detroit]: reading 1 feed(s)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

  mdb-464-20260917.zip: date=20260427 stops=5110 overnight=2531
transit[detroit]: 5110 stops -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/transit/stops/detroit.parquet
Detroit state block groups loaded: 8,340
Detroit city boundary loaded: 1 row(s)
Block groups within city: 622 / 8,340
transit[detroit]: stops matched to a within-city BG: 4,514 / 5,110
transit[detroit]: BG table (622, 12) (596 BGs with >=1 stop)
transit[columbus]: reading 1 feed(s)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

  mdb-404-20260917.zip: date=20260504 stops=2947 overnight=1819
transit[columbus]: 2947 stops -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/transit/stops/columbus.parquet
Columbus state block groups loaded: 9,466
Columbus city boundary loaded: 1 row(s)
Block groups within city: 637 / 9,466
transit[columbus]: stops matched to a within-city BG: 2,194 / 2,947
transit[columbus]: BG table (637, 12) (484 BGs with >=1 stop)
transit: BG feature table (7863, 12) -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/sources/transit.parquet

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

,geoid,city,transit_stop_count,transit_stop_density,transit_nearest_stop_m,transit_service_intensity,transit_overnight_stop_count,transit_overnight_stop_share,transit_risky_stop_count,transit_risky_stop_share,transit_risky_allnight_count,transit_route_mode_diversity
0,170315501002,chicago,2,2.045764,596.019035,106.0,2.0,1.000000,0.0,0.0,0.0,0.0
1,170318350005,chicago,1,8.114573,202.088066,51.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,170313008001,chicago,4,24.531876,194.100323,368.0,4.0,1.000000,0.0,0.0,0.0,0.0
3,170316117002,chicago,3,32.403524,104.384205,186.0,1.0,0.333333,0.0,0.0,0.0,0.0
4,170317104005,chicago,5,17.143641,89.819638,559.0,5.0,1.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7858,390490077104,columbus,3,10.182744,204.924266,213.0,3.0,1.000000,0.0,0.0,0.0,0.0
7859,390490011211,columbus,5,13.466005,255.391269,969.0,5.0,1.000000,0.0,0.0,0.0,0.0
7860,390490088221,columbus,16,8.614147,379.170379,624.0,12.0,0.750000,0.0,0.0,0.0,0.0
7861,390450327031,columbus,0,0.000000,1378.862305,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
7862,390490036001,columbus,7,25.151392,125.473431,324.0,4.0,0.571429,0.0,0.0,0.0,0.0

In [5]:
# What sources are declared, and how each is fetched
for name, src in FEATURE_SOURCES.items():
    print(f"{name:12} backend={src.backend:4} location={src.location:10} "
          f"key={src.key_col:6} cols={src.feature_cols}")

vacancy      backend=bq   location=vacancy    key=geoid  cols=('vacant_pct', 'vacant_pct_lag6')
liens        backend=bq   location=liens      key=geoid  cols=('clip_liens_pct', 'clip_liens_pct_lag6')
foreclosures backend=bq   location=foreclosures key=geoid  cols=('clip_foreclosure_pct', 'clip_foreclosure_pct_lag6')
convenience_stores backend=bq   location=convenience_stores key=geoid  cols=('unq_convenience_stores_clips',)
gas_stations backend=bq   location=gas_stations key=geoid  cols=('unq_gas_stations_clips',)
liquor_stores backend=bq   location=liquor_stores key=geoid  cols=('unq_liquor_stores_clips',)
transit      backend=file location=build via regression_modelling.data_wrangling.transit.build_all_transit key=geoid  cols=('transit_stop_count', 'transit_stop_density', 'transit_nearest_stop_m', 'transit_service_intensity', 'transit_overnight_stop_count', 'transit_overnight_stop_share', 'transit_risky_stop_count', 'transit_risky_stop_share', 'transit_risky_allnight_count', 'transit_route_mode_diversity')
imagery      backend=bq   location=imagery    key=geoid  cols=('roof_condition_avg', 'roof_debris_pct_avg', 'roof_discoloration_pct_avg', 'hardscapes_pct_avg', 'roof_missing_material_pct', 'imagery_structure_count')

In [13]:
# --- Build BQ staging tables (run only when missing or upstream data changed) ---
# Property features build from tables reachable here:
#for name in ["vacancy", "liens", "foreclosures"]:
#    sources.run_bq_build(name)
#    print(f"built {name}")

# Store POIs use the generic sql/build/stores.sql template + STORE_DEFS predicates.
# NOTE: firmographics live in a prd project unreachable from this VM, so run the
# rendered DDL in the BQ console (already done for the 3 stores pulled below):
#for store in ["convenience_stores", "gas_stations", "liquor_stores"]:
#    sources.run_bq_build_store(store)   # -> bg_{store}
#    print(f"built bg_{store}")

In [6]:
# Uncached single pull to confirm BQ auth + schema before running the full pipeline
for source in ["vacancy",
               "liens",
               "foreclosures",
               "gas_stations",
               "liquor_stores",
               "convenience_stores",
               "imagery"]:
    df = sources.run_bq_pull(f"{source}")
    print(f"{source} pull: {df.shape}")

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

vacancy pull: (241456, 5)
liens pull: (241456, 5)
foreclosures pull: (241456, 5)
gas_stations pull: (241456, 4)
liquor_stores pull: (241456, 4)
convenience_stores pull: (241456, 4)
imagery pull: (241362, 7)

In [7]:
# Load liens, vacancy and other parquets saved already
# Check all sources have a geoid column
for name, src in FEATURE_SOURCES.items():
    df = sources.pull_source(src, refresh=True)
    print(f"{name:12} {df.shape}  cols={list(df.columns)}")

vacancy      (241456, 5)  cols=['geoid', 'vacant_pct', 'vacant_pct_lag6', 'vacant_addr', 'total_addr']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

liens        (241456, 5)  cols=['geoid', 'clip_liens_pct', 'clip_liens_pct_lag6', 'total_clips', 'clip_w_liens']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

foreclosures (241456, 5)  cols=['geoid', 'clip_foreclosure_pct', 'clip_foreclosure_pct_lag6', 'total_unq_clips', 'unq_clip_w_foreclosure']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

convenience_stores (241456, 4)  cols=['geoid', 'convenience_stores_clip_pct', 'total_unq_clips', 'unq_convenience_stores_clips']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

gas_stations (241456, 4)  cols=['geoid', 'gas_stations_clip_pct', 'total_unq_clips', 'unq_gas_stations_clips']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

liquor_stores (241456, 4)  cols=['geoid', 'liquor_stores_clip_pct', 'total_unq_clips', 'unq_liquor_stores_clips']
transit      (7863, 12)  cols=['geoid', 'city', 'transit_stop_count', 'transit_stop_density', 'transit_nearest_stop_m', 'transit_service_intensity', 'transit_overnight_stop_count', 'transit_overnight_stop_share', 'transit_risky_stop_count', 'transit_risky_stop_share', 'transit_risky_allnight_count', 'transit_route_mode_diversity']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

imagery      (241362, 7)  cols=['geoid', 'roof_condition_avg', 'roof_debris_pct_avg', 'roof_discoloration_pct_avg', 'hardscapes_pct_avg', 'roof_missing_material_pct', 'imagery_structure_count']

In [8]:
# Load demographic features
demo = features.build_demographic_features(refresh=True)
print("demographic:", demo.shape)
demo.head()

demographic: (242335, 9)

,geoid,det_pct,moved1yr_pct,own_pct,lap_pct,Division,city_centers_dist,pop_est_5mile,pop_ch_1mile
0,020130001001,73.279352,16.042465,28.089888,0.404858,9.0,50.0,2066.0,-37.826087
1,020130001002,57.459677,16.042465,54.318182,13.709677,9.0,50.0,884.0,-11.588785
2,020130001003,75.638051,16.042465,73.684211,10.440835,9.0,50.0,674.0,-32.747604
3,020160001001,33.962264,19.562244,39.766082,3.537736,9.0,50.0,1023.0,-6.250000
4,020160002001,9.478673,24.745302,21.652422,49.052133,9.0,50.0,4411.0,-0.500835

In [9]:
# Assemble features
# NOTE: set refresh to True whenever a new feature is added
feats = features.assemble_features(refresh=True)
print("bg_predictors:", feats.shape)
feats.info()

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

bg_predictors: (242335, 34)
<class 'pandas.DataFrame'>
RangeIndex: 242335 entries, 0 to 242334
Data columns (total 34 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   geoid                         242335 non-null  str
 1   det_pct                       242335 non-null  float64
 2   moved1yr_pct                  242335 non-null  float64
 3   own_pct                       242335 non-null  float64
 4   lap_pct                       242335 non-null  float64
 5   Division                      242335 non-null  float64
 6   city_centers_dist             239780 non-null  float64
 7   pop_est_5mile                 239392 non-null  float64
 8   pop_ch_1mile                  239392 non-null  float64
 9   vacant_pct                    237984 non-null  float64
 10  vacant_pct_lag6               237935 non-null  float64
 11  clip_liens_pct                241273 non-null  float64
 12  clip_liens_pct_lag6           237986 non-null  float64
 13  clip_foreclosure_pct          241273 non-null  float64
 14  clip_foreclosure_pct_lag6     237986 non-null  float64
 15  unq_convenience_stores_clips  241367 non-null  Int64
 16  unq_gas_stations_clips        241367 non-null  Int64
 17  unq_liquor_stores_clips       241367 non-null  Int64
 18  transit_stop_count            7863 non-null    Int64
 19  transit_stop_density          7863 non-null    float64
 20  transit_nearest_stop_m        7863 non-null    float64
 21  transit_service_intensity     7863 non-null    float64
 22  transit_overnight_stop_count  7863 non-null    float64
 23  transit_overnight_stop_share  7863 non-null    float64
 24  transit_risky_stop_count      7863 non-null    float64
 25  transit_risky_stop_share      7863 non-null    float64
 26  transit_risky_allnight_count  7863 non-null    float64
 27  transit_route_mode_diversity  7863 non-null    float64
 28  roof_condition_avg            240479 non-null  float64
 29  roof_debris_pct_avg           240206 non-null  float64
 30  roof_discoloration_pct_avg    240476 non-null  float64
 31  hardscapes_pct_avg            240217 non-null  float64
 32  roof_missing_material_pct     234151 non-null  float64
 33  imagery_structure_count       241273 non-null  Int64
dtypes: Int64(5), float64(28), str(1)
memory usage: 66.8 MB

In [10]:
# Build bias testing table
# NOTE: set refresh to True whenever a new feature is added
bias_feats = build_protected_table(refresh=True)
print("bg_bias_predictors:", bias_feats.shape)
bias_feats.info()

protected table (242335, 4) → /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/bias/protected_attributes.parquet
bg_bias_predictors: (242335, 4)
<class 'pandas.DataFrame'>
RangeIndex: 242335 entries, 0 to 242334
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   geoid             242335 non-null  str
 1   md_hhinc          224390 non-null  float64
 2   wht_pct           242335 non-null  float64
 3   in_household_pct  242335 non-null  float64
dtypes: float64(3), str(1)
memory usage: 10.2 MB

In [11]:
# geoid should be a 12-char string, unique per row
print("geoid dtype :", feats["geoid"].dtype)
print("geoid lengths:", feats["geoid"].str.len().value_counts().to_dict())
print("duplicate geoids:", feats["geoid"].duplicated().sum())

# Non-null coverage per column — low coverage on vacancy/liens flags join or fill issues
print("\nNon-null coverage:")
print((feats.notna().mean() * 100).round(1).astype(str) + "%")

geoid dtype : str
geoid lengths: {12: 242335}
duplicate geoids: 0

Non-null coverage:
geoid                           100.0%
det_pct                         100.0%
moved1yr_pct                    100.0%
own_pct                         100.0%
lap_pct                         100.0%
Division                        100.0%
city_centers_dist                98.9%
pop_est_5mile                    98.8%
pop_ch_1mile                     98.8%
vacant_pct                       98.2%
vacant_pct_lag6                  98.2%
clip_liens_pct                   99.6%
clip_liens_pct_lag6              98.2%
clip_foreclosure_pct             99.6%
clip_foreclosure_pct_lag6        98.2%
unq_convenience_stores_clips     99.6%
unq_gas_stations_clips           99.6%
unq_liquor_stores_clips          99.6%
transit_stop_count                3.2%
transit_stop_density              3.2%
transit_nearest_stop_m            3.2%
transit_service_intensity         3.2%
transit_overnight_stop_count      3.2%
transit_overnight_stop_share      3.2%
transit_risky_stop_count          3.2%
transit_risky_stop_share          3.2%
transit_risky_allnight_count      3.2%
transit_route_mode_diversity      3.2%
roof_condition_avg               99.2%
roof_debris_pct_avg              99.1%
roof_discoloration_pct_avg       99.2%
hardscapes_pct_avg               99.1%
roof_missing_material_pct        96.6%
imagery_structure_count          99.6%
dtype: str

In [12]:
print("Cached source pulls:")
for p in sorted((INTERIM_DIR / "sources").glob("*.parquet")):
    print(" ", p.relative_to(INTERIM_DIR.parent), f"{p.stat().st_size/1e6:.1f} MB")

feat_path = INTERIM_DIR / "features" / "bg_predictors.parquet"
print("\nFeature matrix written:", feat_path.exists(), "→", feat_path)

Cached source pulls:
  interim/sources/convenience_stores.parquet 2.7 MB
  interim/sources/demographic.parquet 9.7 MB
  interim/sources/foreclosures.parquet 3.2 MB
  interim/sources/gas_stations.parquet 2.6 MB
  interim/sources/imagery.parquet 3.6 MB
  interim/sources/liens.parquet 3.0 MB
  interim/sources/liquor_stores.parquet 2.6 MB
  interim/sources/transit.parquet 0.2 MB
  interim/sources/vacancy.parquet 5.2 MB

Feature matrix written: True → /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/features/bg_predictors.parquet