In [3]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
import sys
_here = Path.cwd().resolve()
_root = next(p for p in [_here, *_here.parents] if (p / "src").is_dir())
sys.path.insert(0, str(_root / "src"))

import pandas as pd
from regression_modelling.data_wrangling.dataset import assemble_features
from regression_modelling.data_wrangling.transit.build import build_all_transit
from regression_modelling.constants import FEATURE_SOURCES
from regression_modelling.data_wrangling import sources, features
from regression_modelling.bias_testing.data import build_protected_table
from crime_blockgroup_mapping.config import INTERIM_DIR
from crime_blockgroup_mapping.constants import UCR_YEAR

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
# Assemble all features
assemble_features(refresh=True)

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,geoid,det_pct,moved1yr_pct,own_pct,lap_pct,transit_pct,veh0_pct,in_household_pct,Division,city_centers_dist,...,roof_debris_pct_avg,roof_discoloration_pct_avg,hardscapes_pct_avg,roof_missing_material_pct,imagery_structure_count,roadway_nearest_ramp_m,roadway_nearest_interstate_m,roadway_ramp_count,roadway_arterial_density,roadway_intersection_density
0,020130001001,73.279352,16.042465,28.089888,0.404858,0.265369,25.545455,65.293602,9.0,50.0,...,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
1,020130001002,57.459677,16.042465,54.318182,13.709677,0.265369,25.545455,65.293602,9.0,50.0,...,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
2,020130001003,75.638051,16.042465,73.684211,10.440835,0.265369,25.545455,65.293602,9.0,50.0,...,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
3,020160001001,33.962264,19.562244,39.766082,3.537736,1.204819,28.947368,66.310160,9.0,50.0,...,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN
4,020160002001,9.478673,24.745302,21.652422,49.052133,0.000000,2.030735,68.261851,9.0,50.0,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242330,560459511001,75.646259,10.689127,84.615385,5.714286,8.915305,0.000000,92.305380,8.0,50.0,...,0.05,1.76,1.68,0.42,2740,NaN,NaN,NaN,NaN,NaN
242331,560459511002,85.407240,10.689127,95.839112,0.000000,8.915305,0.000000,92.305380,8.0,50.0,...,0.06,2.27,1.03,0.44,5221,NaN,NaN,NaN,NaN,NaN
242332,560459513001,74.054983,13.644165,88.980716,0.000000,3.583815,0.982659,96.636260,8.0,50.0,...,0.07,2.41,3.62,0.42,1651,NaN,NaN,NaN,NaN,NaN
242333,560459513002,67.576244,13.644165,84.787018,20.866774,3.583815,0.982659,96.636260,8.0,50.0,...,0.05,2.53,3.80,0.50,1583,NaN,NaN,NaN,NaN,NaN
242334,560459513003,59.021922,13.644165,88.703704,0.000000,3.583815,0.982659,96.636260,8.0,50.0,...,0.06,1.83,3.73,0.43,1848,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Building transit features from Mobility zip files 
build_all_transit(refresh=False)   # rebuilds data/interim/sources/transit.parquet from the new zips

transit: facility 'atm' unavailable (Forbidden); H1/H3 skipped for it
Chicago state block groups loaded: 9,896
Chicago city boundary loaded: 1 row(s)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Block groups within city: 2,164 / 9,896
transit[chicago]: stops matched to a within-city BG: 9,971 / 10,827
transit[chicago]: BG table (2164, 12) (2009 BGs with >=1 stop)
Houston state block groups loaded: 18,626
Houston city boundary loaded: 1 row(s)
Block groups within city: 1,629 / 18,626

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

transit[houston]: stops matched to a within-city BG: 7,853 / 8,797
transit[houston]: BG table (1629, 12) (1279 BGs with >=1 stop)
Atlanta state block groups loaded: 7,441
Atlanta city boundary loaded: 1 row(s)
Block groups within city: 426 / 7,441
transit[atlanta]: stops matched to a within-city BG: 2,504 / 6,924
transit[atlanta]: BG table (426, 12) (358 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

San Francisco state block groups loaded: 25,586
San Francisco city boundary loaded: 1 row(s)
Block groups within city: 679 / 25,586
transit[san_francisco]: stops matched to a within-city BG: 3,197 / 3,258
transit[san_francisco]: BG table (679, 12) (622 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Pittsburgh state block groups loaded: 10,172
Pittsburgh city boundary loaded: 1 row(s)
Block groups within city: 317 / 10,172
transit[pittsburgh]: stops matched to a within-city BG: 2,676 / 6,418
transit[pittsburgh]: BG table (317, 12) (299 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Jacksonville state block groups loaded: 13,350
Jacksonville city boundary loaded: 1 row(s)
Block groups within city: 550 / 13,350
transit[jacksonville]: stops matched to a within-city BG: 2,291 / 2,390
transit[jacksonville]: BG table (550, 12) (386 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Kansas City state block groups loaded: 5,031
Kansas City city boundary loaded: 1 row(s)
Block groups within city: 473 / 5,031
transit[kansas_city]: stops matched to a within-city BG: 1,903 / 2,283
transit[kansas_city]: BG table (473, 12) (321 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Sacramento state block groups loaded: 25,586
Sacramento city boundary loaded: 1 row(s)
Block groups within city: 366 / 25,586
transit[sacramento]: stops matched to a within-city BG: 1,502 / 2,821
transit[sacramento]: BG table (366, 12) (303 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Detroit state block groups loaded: 8,340
Detroit city boundary loaded: 1 row(s)
Block groups within city: 622 / 8,340
transit[detroit]: stops matched to a within-city BG: 4,514 / 5,110
transit[detroit]: BG table (622, 12) (596 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Columbus state block groups loaded: 9,466
Columbus city boundary loaded: 1 row(s)
Block groups within city: 637 / 9,466
transit[columbus]: stops matched to a within-city BG: 2,194 / 2,947
transit[columbus]: BG table (637, 12) (484 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Philadelphia state block groups loaded: 10,172
Philadelphia city boundary loaded: 1 row(s)
Block groups within city: 1,338 / 10,172
transit[philadelphia]: stops matched to a within-city BG: 8,055 / 13,596
transit[philadelphia]: BG table (1338, 12) (1258 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Milwaukee state block groups loaded: 4,678
Milwaukee city boundary loaded: 1 row(s)
Block groups within city: 567 / 4,678
transit[milwaukee]: stops matched to a within-city BG: 2,595 / 3,684
transit[milwaukee]: BG table (567, 12) (528 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Baltimore state block groups loaded: 4,068
Baltimore city boundary loaded: 1 row(s)
Block groups within city: 618 / 4,068
transit[baltimore]: stops matched to a within-city BG: 2,625 / 4,077

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

transit[baltimore]: BG table (618, 12) (560 BGs with >=1 stop)
Washington DC state block groups loaded: 571
Washington DC city boundary loaded: 1 row(s)
Block groups within city: 571 / 571
transit[dc]: stops matched to a within-city BG: 2,935 / 9,362
transit[dc]: BG table (571, 12) (537 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Oakland state block groups loaded: 25,586
Oakland city boundary loaded: 1 row(s)
Block groups within city: 353 / 25,586
transit[oakland]: stops matched to a within-city BG: 1,579 / 4,763
transit[oakland]: BG table (353, 12) (327 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

New York state block groups loaded: 15,965
New York city boundary loaded: 1 row(s)
Block groups within city: 6,712 / 15,965
transit[new_york]: stops matched to a within-city BG: 13,791 / 13,871

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

transit[new_york]: BG table (6712, 12) (4879 BGs with >=1 stop)
Dallas state block groups loaded: 18,626
Dallas city boundary loaded: 1 row(s)
Block groups within city: 869 / 18,626
transit[dallas]: stops matched to a within-city BG: 4,714 / 6,957
transit[dallas]: BG table (869, 12) (720 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Denver state block groups loaded: 4,058
Denver city boundary loaded: 1 row(s)
Block groups within city: 572 / 4,058
transit[denver]: stops matched to a within-city BG: 2,448 / 7,008

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

transit[denver]: BG table (572, 12) (521 BGs with >=1 stop)
Las Vegas state block groups loaded: 1,963
Las Vegas city boundary loaded: 1 row(s)
Block groups within city: 439 / 1,963
transit[las_vegas]: stops matched to a within-city BG: 1,264 / 3,750
transit[las_vegas]: BG table (439, 12) (343 BGs with >=1 stop)

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

Seattle state block groups loaded: 5,299
Seattle city boundary loaded: 1 row(s)
Block groups within city: 537 / 5,299
transit[seattle]: stops matched to a within-city BG: 2,611 / 6,389
transit[seattle]: BG table (537, 12) (500 BGs with >=1 stop)
transit: BG feature table (20439, 12) -> /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/sources/transit.parquet

/home/eprashar_solutions_corelogic_com/crime-idx-2026/src/crime_blockgroup_mapping/boundaries.py:30: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  bg['centroid'] = bg.geometry.centroid

,geoid,city,transit_stop_count,transit_stop_density,transit_nearest_stop_m,transit_service_intensity,transit_overnight_stop_count,transit_overnight_stop_share,transit_risky_stop_count,transit_risky_stop_share,transit_risky_allnight_count,transit_route_mode_diversity
0,170315501002,chicago,2,2.045764,596.019035,106.0,2.0,1.000000,0.0,0.000000,0.0,0.000000
1,170318350005,chicago,1,8.114573,202.088066,51.0,0.0,0.000000,1.0,1.000000,0.0,0.000000
2,170313008001,chicago,4,24.531876,194.100323,368.0,4.0,1.000000,3.0,0.750000,3.0,0.000000
3,170316117002,chicago,3,32.403524,104.384205,186.0,1.0,0.333333,2.0,0.666667,0.0,0.000000
4,170317104005,chicago,5,17.143641,89.819638,559.0,5.0,1.000000,0.0,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
20434,530330110012,seattle,8,18.797728,198.374636,1040.0,8.0,1.000000,2.0,0.250000,2.0,0.543564
20435,530330025001,seattle,5,7.915660,55.519207,271.0,3.0,0.600000,2.0,0.400000,1.0,0.000000
20436,530330115002,seattle,13,24.742370,18.472508,921.0,7.0,0.538462,4.0,0.307692,3.0,0.000000
20437,530330043011,seattle,6,17.463012,240.596793,502.0,4.0,0.666667,3.0,0.500000,3.0,0.000000
20438,530330102002,seattle,6,1.774700,737.724326,313.0,6.0,1.000000,2.0,0.333333,2.0,0.000000

In [3]:
# What sources are declared, and how each is fetched
for name, src in FEATURE_SOURCES.items():
    print(f"{name:12} backend={src.backend:4} location={src.location:10} "
          f"key={src.key_col:6} cols={src.feature_cols}")

vacancy      backend=bq   location=vacancy    key=geoid  cols=('vacant_pct', 'vacant_pct_lag6')
liens        backend=bq   location=liens      key=geoid  cols=('clip_liens_pct', 'clip_liens_pct_lag6')
foreclosures backend=bq   location=foreclosures key=geoid  cols=('clip_foreclosure_pct', 'clip_foreclosure_pct_lag6')
transactions backend=bq   location=transactions key=geoid  cols=('clip_transaction_pct', 'clip_transaction_pct_lag6')
convenience_stores backend=bq   location=convenience_stores key=geoid  cols=('unq_convenience_stores_clips',)
gas_stations backend=bq   location=gas_stations key=geoid  cols=('unq_gas_stations_clips',)
liquor_stores backend=bq   location=liquor_stores key=geoid  cols=('unq_liquor_stores_clips',)
transit      backend=file location=build via regression_modelling.data_wrangling.transit.build_all_transit key=geoid  cols=('transit_stop_count', 'transit_stop_density', 'transit_nearest_stop_m', 'transit_service_intensity', 'transit_overnight_stop_count', 'transit_overnight_stop_share', 'transit_risky_stop_count', 'transit_risky_stop_share', 'transit_risky_allnight_count', 'transit_route_mode_diversity')
imagery      backend=bq   location=imagery    key=geoid  cols=('roof_condition_avg', 'roof_debris_pct_avg', 'roof_discoloration_pct_avg', 'hardscapes_pct_avg', 'roof_missing_material_pct', 'imagery_structure_count')
roadway      backend=file location=build via regression_modelling.data_wrangling.roadway.build_all_roadway key=geoid  cols=('roadway_nearest_ramp_m', 'roadway_nearest_interstate_m', 'roadway_ramp_count', 'roadway_arterial_density', 'roadway_intersection_density')

In [ ]:
# NOTE: Only BQ sources from the previous cell's output go in this list
# Uncached single pull to confirm BQ auth + schema before running the full pipeline
for source in ["vacancy",
               "transactions",
               "liens",
               "foreclosures",
               "gas_stations",
               "liquor_stores",
               "convenience_stores",
               #"transit",
               #"roadway",
               "imagery"]:
    df = sources.run_bq_pull(f"{source}")
    print(f"{source} pull: {df.shape}")

vacancy pull: (241456, 5)
transactions pull: (241272, 5)
liens pull: (241272, 5)
foreclosures pull: (241272, 6)
gas_stations pull: (241272, 4)
liquor_stores pull: (241272, 4)
convenience_stores pull: (241272, 4)
imagery pull: (241362, 7)

In [6]:
# Load liens, vacancy and other parquets saved already
# Check all sources have a geoid column
for name, src in FEATURE_SOURCES.items():
    df = sources.pull_source(src, refresh=True)
    print(f"{name:12} {df.shape}  cols={list(df.columns)}")

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

vacancy      (241456, 5)  cols=['geoid', 'vacant_pct', 'vacant_pct_lag6', 'vacant_addr', 'total_addr']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

liens        (241272, 5)  cols=['geoid', 'clip_liens_pct', 'clip_liens_pct_lag6', 'total_clips', 'clip_w_liens']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

foreclosures (241272, 6)  cols=['geoid', 'clip_foreclosure_pct', 'clip_foreclosure_pct_lag6', 'total_unq_clips', 'unq_clip_w_transaction', 'unq_clip_w_foreclosure']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

transactions (241272, 5)  cols=['geoid', 'clip_transaction_pct', 'clip_transaction_pct_lag6', 'total_unq_clips', 'unq_clip_w_transaction']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

convenience_stores (241272, 4)  cols=['geoid', 'convenience_stores_clip_pct', 'total_unq_clips', 'unq_convenience_stores_clips']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

gas_stations (241272, 4)  cols=['geoid', 'gas_stations_clip_pct', 'total_unq_clips', 'unq_gas_stations_clips']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

liquor_stores (241272, 4)  cols=['geoid', 'liquor_stores_clip_pct', 'total_unq_clips', 'unq_liquor_stores_clips']
transit      (20439, 12)  cols=['geoid', 'city', 'transit_stop_count', 'transit_stop_density', 'transit_nearest_stop_m', 'transit_service_intensity', 'transit_overnight_stop_count', 'transit_overnight_stop_share', 'transit_risky_stop_count', 'transit_risky_stop_share', 'transit_risky_allnight_count', 'transit_route_mode_diversity']

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

imagery      (241362, 7)  cols=['geoid', 'roof_condition_avg', 'roof_debris_pct_avg', 'roof_discoloration_pct_avg', 'hardscapes_pct_avg', 'roof_missing_material_pct', 'imagery_structure_count']
roadway      (7863, 7)  cols=['geoid', 'city', 'roadway_nearest_ramp_m', 'roadway_nearest_interstate_m', 'roadway_ramp_count', 'roadway_arterial_density', 'roadway_intersection_density']

In [7]:
# Load demographic features
demo = features.build_demographic_features(refresh=True)
print("demographic:", demo.shape)
demo.head()

demographic: (242335, 12)

,geoid,det_pct,moved1yr_pct,own_pct,lap_pct,transit_pct,veh0_pct,in_household_pct,Division,city_centers_dist,pop_est_5mile,pop_ch_1mile
0,020130001001,73.279352,16.042465,28.089888,0.404858,0.265369,25.545455,65.293602,9.0,50.0,2066.0,-37.826087
1,020130001002,57.459677,16.042465,54.318182,13.709677,0.265369,25.545455,65.293602,9.0,50.0,884.0,-11.588785
2,020130001003,75.638051,16.042465,73.684211,10.440835,0.265369,25.545455,65.293602,9.0,50.0,674.0,-32.747604
3,020160001001,33.962264,19.562244,39.766082,3.537736,1.204819,28.947368,66.310160,9.0,50.0,1023.0,-6.250000
4,020160002001,9.478673,24.745302,21.652422,49.052133,0.000000,2.030735,68.261851,9.0,50.0,4411.0,-0.500835

In [8]:
# Assemble features
# NOTE: set refresh to True whenever a new feature is added
feats = features.assemble_features(refresh=True)
print("bg_predictors:", feats.shape)
feats.info()

/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(
/home/eprashar_solutions_corelogic_com/.cache/pypoetry/virtualenvs/crime-idx-2026-v3aYThD0-py3.12/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

bg_predictors: (242335, 44)
<class 'pandas.DataFrame'>
RangeIndex: 242335 entries, 0 to 242334
Data columns (total 44 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   geoid                         242335 non-null  str
 1   det_pct                       242335 non-null  float64
 2   moved1yr_pct                  242335 non-null  float64
 3   own_pct                       242335 non-null  float64
 4   lap_pct                       242335 non-null  float64
 5   transit_pct                   242335 non-null  float64
 6   veh0_pct                      242335 non-null  float64
 7   in_household_pct              242335 non-null  float64
 8   Division                      242335 non-null  float64
 9   city_centers_dist             239780 non-null  float64
 10  pop_est_5mile                 239392 non-null  float64
 11  pop_ch_1mile                  239392 non-null  float64
 12  vacant_pct                    237989 non-null  float64
 13  vacant_pct_lag6               237939 non-null  float64
 14  clip_liens_pct                241185 non-null  float64
 15  clip_liens_pct_lag6           237819 non-null  float64
 16  clip_foreclosure_pct          236689 non-null  float64
 17  clip_foreclosure_pct_lag6     235065 non-null  float64
 18  clip_transaction_pct          241185 non-null  float64
 19  clip_transaction_pct_lag6     237819 non-null  float64
 20  unq_convenience_stores_clips  241185 non-null  Int64
 21  unq_gas_stations_clips        241185 non-null  Int64
 22  unq_liquor_stores_clips       241185 non-null  Int64
 23  transit_stop_count            20439 non-null   Int64
 24  transit_stop_density          20439 non-null   float64
 25  transit_nearest_stop_m        20439 non-null   float64
 26  transit_service_intensity     20439 non-null   float64
 27  transit_overnight_stop_count  20439 non-null   float64
 28  transit_overnight_stop_share  20439 non-null   float64
 29  transit_risky_stop_count      20439 non-null   float64
 30  transit_risky_stop_share      20439 non-null   float64
 31  transit_risky_allnight_count  20439 non-null   float64
 32  transit_route_mode_diversity  20439 non-null   float64
 33  roof_condition_avg            240479 non-null  float64
 34  roof_debris_pct_avg           240206 non-null  float64
 35  roof_discoloration_pct_avg    240476 non-null  float64
 36  hardscapes_pct_avg            240217 non-null  float64
 37  roof_missing_material_pct     234151 non-null  float64
 38  imagery_structure_count       241273 non-null  Int64
 39  roadway_nearest_ramp_m        7863 non-null    float64
 40  roadway_nearest_interstate_m  7863 non-null    float64
 41  roadway_ramp_count            7863 non-null    float64
 42  roadway_arterial_density      7863 non-null    float64
 43  roadway_intersection_density  7863 non-null    float64
dtypes: Int64(5), float64(38), str(1)
memory usage: 85.3 MB

In [9]:
# Build bias testing table
# NOTE: set refresh to True whenever a new feature is added
bias_feats = build_protected_table(refresh=True)
print("bg_bias_predictors:", bias_feats.shape)
bias_feats.info()

protected table (242335, 4) → /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/bias/protected_attributes.parquet
bg_bias_predictors: (242335, 4)
<class 'pandas.DataFrame'>
RangeIndex: 242335 entries, 0 to 242334
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   geoid             242335 non-null  str
 1   md_hhinc          224390 non-null  float64
 2   wht_pct           242335 non-null  float64
 3   in_household_pct  242335 non-null  float64
dtypes: float64(3), str(1)
memory usage: 10.2 MB

In [10]:
# geoid should be a 12-char string, unique per row
print("geoid dtype :", feats["geoid"].dtype)
print("geoid lengths:", feats["geoid"].str.len().value_counts().to_dict())
print("duplicate geoids:", feats["geoid"].duplicated().sum())

# Non-null coverage per column — low coverage on vacancy/liens flags join or fill issues
print("\nNon-null coverage:")
print((feats.notna().mean() * 100).round(1).astype(str) + "%")

geoid dtype : str
geoid lengths: {12: 242335}
duplicate geoids: 0

Non-null coverage:
geoid                           100.0%
det_pct                         100.0%
moved1yr_pct                    100.0%
own_pct                         100.0%
lap_pct                         100.0%
transit_pct                     100.0%
veh0_pct                        100.0%
in_household_pct                100.0%
Division                        100.0%
city_centers_dist                98.9%
pop_est_5mile                    98.8%
pop_ch_1mile                     98.8%
vacant_pct                       98.2%
vacant_pct_lag6                  98.2%
clip_liens_pct                   99.5%
clip_liens_pct_lag6              98.1%
clip_foreclosure_pct             97.7%
clip_foreclosure_pct_lag6        97.0%
clip_transaction_pct             99.5%
clip_transaction_pct_lag6        98.1%
unq_convenience_stores_clips     99.5%
unq_gas_stations_clips           99.5%
unq_liquor_stores_clips          99.5%
transit_stop_count                8.4%
transit_stop_density              8.4%
transit_nearest_stop_m            8.4%
transit_service_intensity         8.4%
transit_overnight_stop_count      8.4%
transit_overnight_stop_share      8.4%
transit_risky_stop_count          8.4%
transit_risky_stop_share          8.4%
transit_risky_allnight_count      8.4%
transit_route_mode_diversity      8.4%
roof_condition_avg               99.2%
roof_debris_pct_avg              99.1%
roof_discoloration_pct_avg       99.2%
hardscapes_pct_avg               99.1%
roof_missing_material_pct        96.6%
imagery_structure_count          99.6%
roadway_nearest_ramp_m            3.2%
roadway_nearest_interstate_m      3.2%
roadway_ramp_count                3.2%
roadway_arterial_density          3.2%
roadway_intersection_density      3.2%
dtype: str

In [11]:
print("Cached source pulls:")
for p in sorted((INTERIM_DIR / "sources").glob("*.parquet")):
    print(" ", p.relative_to(INTERIM_DIR.parent), f"{p.stat().st_size/1e6:.1f} MB")

feat_path = INTERIM_DIR / "features" / "bg_predictors.parquet"
print("\nFeature matrix written:", feat_path.exists(), "→", feat_path)

Cached source pulls:
  interim/sources/convenience_stores.parquet 2.7 MB
  interim/sources/demographic.parquet 11.8 MB
  interim/sources/foreclosures.parquet 3.5 MB
  interim/sources/gas_stations.parquet 2.6 MB
  interim/sources/imagery.parquet 3.6 MB
  interim/sources/liens.parquet 2.9 MB
  interim/sources/liquor_stores.parquet 2.6 MB
  interim/sources/roadway.parquet 0.4 MB
  interim/sources/transactions.parquet 3.8 MB
  interim/sources/transit.parquet 0.7 MB
  interim/sources/vacancy.parquet 5.1 MB

Feature matrix written: True → /home/eprashar_solutions_corelogic_com/crime-idx-2026/data/interim/features/bg_predictors.parquet